### ISSUE TITLE
I want to maintain this project. 

### ISSUE THREAD

**Issue by arnabwahid** [arnabwahid/wordpress-bootstrap#252]
@sbaxter @chrisbarnes I wish to maintain this project, keep it up to date with future WordPress releases and oversee community contributions. Would you consider handing it over?

**Comment by chrisbarnes** [comment]
Definitely. I can hand it over to you Arnab.

**Comment by arnabwahid** [comment]
Thanks Chris. I'll be ready when you are.

**Comment by chrisbarnes** [comment]
@arnabwahid You should be good to go. Thanks!

**Comment by arnabwahid** [comment]
@chrisbarnes First thing I would do is setup a test suite for continuous integration. Update assets, and then handle PRs. I will keep you updated if you like. Let is know, if you are okay if I ping you once in a blue moon for your opinion on tricky decisions. I'd be great to stay in touch. Thanks!
